//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServidorAhorcado.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partida
    {
        public int IdPartida { get; set; }
        public string NombrePartida { get; set; }
        public Nullable<System.DateTime> FechaFin { get; set; }
        public Nullable<int> EstadoId { get; set; }
        public Nullable<int> JugadorAId { get; set; }
        public Nullable<int> JugadorBId { get; set; }
        public Nullable<int> PalabraId { get; set; }
        public Nullable<int> IdiomaId { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
    
        public virtual Estado Estado { get; set; }
        public virtual Idioma Idioma { get; set; }
        public virtual Jugador Jugador { get; set; }
        public virtual Jugador Jugador1 { get; set; }
        public virtual Palabra Palabra { get; set; }
    }
}
